-- MySQL Script generated by MySQL Workbench
-- Sun Apr  7 23:07:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
  `categorieID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`categorieID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fuels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fuels` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fuels` (
  `fuelID` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`fuelID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Engines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Engines` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Engines` (
  `engineID` INT NOT NULL AUTO_INCREMENT,
  `fuelConsumption` FLOAT NOT NULL,
  `power` INT NOT NULL,
  `Enginescol` FLOAT NULL,
  PRIMARY KEY (`engineID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Positions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Positions` (
  `positionID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`positionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employees` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employees` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(150) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_nr` VARCHAR(20) NOT NULL,
  `positionID` INT NOT NULL,
  PRIMARY KEY (`employeeID`),
  INDEX `fk_Employees_Positions1_idx` (`positionID` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Positions1`
    FOREIGN KEY (`positionID`)
    REFERENCES `mydb`.`Positions` (`positionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transactions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transactions` (
  `transactionID` INT NOT NULL AUTO_INCREMENT,
  `transactionDate` DATE NOT NULL,
  `transactionValue` FLOAT NULL,
  PRIMARY KEY (`transactionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cars` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cars` (
  `carID` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(200) NOT NULL,
  `model` VARCHAR(255) NOT NULL,
  `vin` CHAR(17) NOT NULL,
  `driveType` CHAR(3) NOT NULL,
  `mileage` INT NOT NULL DEFAULT 120000,
  `color` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `Engines_engineID` INT NOT NULL,
  `fuelID` INT NOT NULL,
  `categorieID` INT NOT NULL,
  `transactionID` INT NOT NULL,
  PRIMARY KEY (`carID`),
  INDEX `fk_Cars_Engines_idx` (`Engines_engineID` ASC) VISIBLE,
  INDEX `fk_Cars_Fuels1_idx` (`fuelID` ASC) VISIBLE,
  INDEX `fk_Cars_Categories1_idx` (`categorieID` ASC) VISIBLE,
  INDEX `fk_Cars_Transactions1_idx` (`transactionID` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_Engines`
    FOREIGN KEY (`Engines_engineID`)
    REFERENCES `mydb`.`Engines` (`engineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_Fuels1`
    FOREIGN KEY (`fuelID`)
    REFERENCES `mydb`.`Fuels` (`fuelID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_Categories1`
    FOREIGN KEY (`categorieID`)
    REFERENCES `mydb`.`Categories` (`categorieID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_Transactions1`
    FOREIGN KEY (`transactionID`)
    REFERENCES `mydb`.`Transactions` (`transactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `cliantID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(150) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `nr_tel` VARCHAR(20) NOT NULL,
  `transactionID` INT NOT NULL,
  PRIMARY KEY (`cliantID`),
  INDEX `fk_Clients_Transactions1_idx` (`transactionID` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Transactions1`
    FOREIGN KEY (`transactionID`)
    REFERENCES `mydb`.`Transactions` (`transactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
