version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks: 
     - network-backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: example_root_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks: 
     - network-backend

  backend:
    build: ./cdeler_back
    container_name: backend
    environment:
      DATABASE_URL: mysql://root:example_root_password@db:3306/cdeler
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./cdeler_back:/app
      - /app/node_modules
    networks: 
     - network-backend

  frontend:
    build: ./cdeler_front
    container_name: frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./cdeler_front:/app
      - /app/node_modules
    networks: 
     - network-backend

networks:
  network-backend:

volumes:
  db_data: